# test-script for QUTest unit testing harness
# see https://www.state-machine.com/qtools/qutest.html

# preamble...
def on_reset():
    expect_pause()
    glb_filter(GRP_ALL)
    continue_test()
    expect("@timestamp AO-Subsc Obj=Philo::inst[0],Sig=EAT_SIG")
    expect("@timestamp AO-Subsc Obj=Philo::inst[0],Sig=TEST_SIG")
    expect("===RTC===> St-Init  Obj=Philo::inst[0],State=QP::QHsm::top->Philo::thinking")
    expect("@timestamp BSP_CALL BSP::random *")
    expect("@timestamp TE0-Arm  Obj=Philo::inst[0].m_timeEvt,AO=Philo::inst[0],Tim=*,Int=0")
    expect("===RTC===> St-Entry Obj=Philo::inst[0],State=Philo::thinking")
    expect("@timestamp Init===> Obj=Philo::inst[0],State=Philo::thinking")
    expect("@timestamp AO-Subsc Obj=Philo::inst[1],Sig=EAT_SIG")
    expect("@timestamp AO-Subsc Obj=Philo::inst[1],Sig=TEST_SIG")
    expect("===RTC===> St-Init  Obj=Philo::inst[1],State=QP::QHsm::top->Philo::thinking")
    expect("@timestamp BSP_CALL BSP::random *")
    expect("@timestamp TE0-Arm  Obj=Philo::inst[1].m_timeEvt,AO=Philo::inst[1],Tim=*,Int=0")
    expect("===RTC===> St-Entry Obj=Philo::inst[1],State=Philo::thinking")
    expect("@timestamp Init===> Obj=Philo::inst[1],State=Philo::thinking")
    expect("@timestamp AO-Subsc Obj=Philo::inst[2],Sig=EAT_SIG")
    expect("@timestamp AO-Subsc Obj=Philo::inst[2],Sig=TEST_SIG")
    expect("===RTC===> St-Init  Obj=Philo::inst[2],State=QP::QHsm::top->Philo::thinking")
    expect("@timestamp BSP_CALL BSP::random *")
    expect("@timestamp TE0-Arm  Obj=Philo::inst[2].m_timeEvt,AO=Philo::inst[2],Tim=*,Int=0")
    expect("===RTC===> St-Entry Obj=Philo::inst[2],State=Philo::thinking")
    expect("@timestamp Init===> Obj=Philo::inst[2],State=Philo::thinking")
    expect("@timestamp AO-Subsc Obj=Philo::inst[3],Sig=EAT_SIG")
    expect("@timestamp AO-Subsc Obj=Philo::inst[3],Sig=TEST_SIG")
    expect("===RTC===> St-Init  Obj=Philo::inst[3],State=QP::QHsm::top->Philo::thinking")
    expect("@timestamp BSP_CALL BSP::random *")
    expect("@timestamp TE0-Arm  Obj=Philo::inst[3].m_timeEvt,AO=Philo::inst[3],Tim=*,Int=0")
    expect("===RTC===> St-Entry Obj=Philo::inst[3],State=Philo::thinking")
    expect("@timestamp Init===> Obj=Philo::inst[3],State=Philo::thinking")
    expect("@timestamp AO-Subsc Obj=Philo::inst[4],Sig=EAT_SIG")
    expect("@timestamp AO-Subsc Obj=Philo::inst[4],Sig=TEST_SIG")
    expect("===RTC===> St-Init  Obj=Philo::inst[4],State=QP::QHsm::top->Philo::thinking")
    expect("@timestamp BSP_CALL BSP::random *")
    expect("@timestamp TE0-Arm  Obj=Philo::inst[4].m_timeEvt,AO=Philo::inst[4],Tim=*,Int=0")
    expect("===RTC===> St-Entry Obj=Philo::inst[4],State=Philo::thinking")
    expect("@timestamp Init===> Obj=Philo::inst[4],State=Philo::thinking")
    expect("@timestamp AO-Subsc Obj=Table::inst,Sig=DONE_SIG")
    expect("@timestamp AO-Subsc Obj=Table::inst,Sig=PAUSE_SIG")
    expect("@timestamp AO-Subsc Obj=Table::inst,Sig=SERVE_SIG")
    expect("@timestamp AO-Subsc Obj=Table::inst,Sig=TEST_SIG")
    expect("@timestamp BSP_CALL BSP::displayPhilStat 0 thinking")
    expect("@timestamp BSP_CALL BSP::displayPhilStat 1 thinking")
    expect("@timestamp BSP_CALL BSP::displayPhilStat 2 thinking")
    expect("@timestamp BSP_CALL BSP::displayPhilStat 3 thinking")
    expect("@timestamp BSP_CALL BSP::displayPhilStat 4 thinking")
    expect("===RTC===> St-Init  Obj=Table::inst,State=QP::QHsm::top->Table::serving")
    expect("===RTC===> St-Entry Obj=Table::inst,State=Table::serving")
    expect("@timestamp Init===> Obj=Table::inst,State=Table::serving")
    expect_run()

test("DPP init")
